# Generated by Django 3.0.5 on 2020-04-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('cover_url', models.URLField(max_length=127)),
                ('quantity', models.CharField(max_length=3)),
            ],
        ),
    ]
