# Generated by Django 3.0.5 on 2020-04-28 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donated_books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('donation_request', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.DonationRequest')),
            ],
        ),
    ]
