# Generated by Django 3.0.5 on 2020-04-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donated_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='donated',
            field=models.CharField(default="<span class='label label-info'>Not Donated</span>", max_length=200),
        ),
    ]
