# Generated by Django 3.0.5 on 2020-04-25 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200425_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationrequest',
            old_name='library',
            new_name='destination',
        ),
    ]
