# Generated by Django 3.0.5 on 2020-04-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_donationrequest_donated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='donated',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='not_donated',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='yes_donated',
            field=models.CharField(default='', max_length=200),
        ),
    ]
