# Generated by Django 3.0.5 on 2020-04-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200429_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='not_donated',
        ),
        migrations.RemoveField(
            model_name='donationrequest',
            name='yes_donated',
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='donated_or_not',
            field=models.CharField(default='<span class="label label-info">Not Donated</span>', max_length=200),
        ),
    ]
